### ISSUE TITLE
Clicking a link shifts focus to Google Chrome (one of my browsers), then a second click opens up Browserosaurus

### ISSUE THREAD

**Issue by simongade** [will-stone/browserosaurus#668] opened 2023-11-14 20:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

I click a link (I've tried Mimestream, in Apple Messages, and the "Report an issue" button in Browserosaurus Preferences). This shifts focus to Google Chrome which is on another Space. When I then switch back to my original Space and click the link again, Browserosaurus opens fine.

### Expected Behaviour

Open Browserosaurus directly.

### Steps To Reproduce

1. Click link
2. 

### Browserosaurus version

20.6.0

### macOS version

14.1.1.

### CPU Architecture

ARM

**Comment by will-stone** [comment] 2023-11-14 22:07
Hi. Is Chrome in full screen mode (green window button)?

**Comment by simongade** [comment] 2023-11-14 22:34
No, just a normal window.

I'm using Profiles in Chrome, in case that has anything to do with it.

Simon

**Comment by will-stone** [comment] 2023-11-15 06:44
Oh sorry, you said “in another space”, missed that first time around. That’s a dupe of this one: https://github.com/will-stone/browserosaurus/issues/595 and unfortunately it’s something that affects the underlying framework that B is built upon, so not something I’m able to fix right now.

**Closed by will-stone** 2023-11-15 06:44 UTC
Labels: bug
