### ISSUE TITLE
v11 Feedback

### ISSUE THREAD

**Issue by i0ntempest** [will-stone/browserosaurus#288] opened 2020-09-01 20:39 UTC
To be honest I prefer the "tiled and spaced-out icons with names" style in v10. Maybe there could be a switch so we can choose a preferred style?

**Comment by will-stone** [comment] 2020-09-01 20:49
Thanks for your feedback. However, I cannot maintain two versions of the app, when I only use one. I've found the new layout works particularly well when you have 6 or more browsers, because v10 would force this on to two rows. I'm happy to see any tweaks on the new design. Also, you can download the source for v10 and turn off the auto-updater if you wish to stay on v10.

**Comment by i0ntempest** [comment] 2020-09-01 21:31
Okay I understand. If that's the case, I'd say maybe space out the icons instead of aligning to the left, if that's good with you?

**Comment by will-stone** [comment] 2020-09-02 07:44
Oh this took the longest part of the whole redesign, so I appreciate your concerns. I tried a lot of different combinations. The issue is we're designing for an unknown: an unknown amount of browsers. For example, this is what my current setup looks like:

<img width="912" alt="Browserosaurus 2020-09-02 08-10-35" src="https://user-images.githubusercontent.com/654103/91944653-575c5400-ecf6-11ea-932b-56fc802c2c3a.png">

If I set the spacing to `justify-content: around`, it doesn't look too bad:

<img width="912" alt="Browserosaurus 2020-09-02 08-26-01" src="https://user-images.githubusercontent.com/654103/91944715-70fd9b80-ecf6-11ea-9bd7-09601dc8b996.png">

However this then looks awkward when we have only two browsers:

<img width="912" alt="Browserosaurus 2020-09-02 08-26-19" src="https://user-images.githubusercontent.com/654103/91948351-bec6d380-ecf7-11ea-897a-2c90aff39d1a.png">

My hope is that, using from-the-left, scans well and is offset by the status-bar buttons in the bottom-right of the picker window.

How many browsers do you have visible in Browserosaurus?

**Comment by will-stone** [comment] 2020-09-02 07:55
The issue, really, is the URL bar. If it wasn't for that, we could display the browser like the dock or the cmd-tab window. Here's a quick idea I just had, but I'd need to explore it further, and it probably won't be for a while so people can get used to v11.

![image](https://user-images.githubusercontent.com/654103/91954629-f767ac80-ecf9-11ea-9bd1-7865914427ef.png)

**Comment by i0ntempest** [comment] 2020-09-02 08:31
I have 5 browsers and they're all crammed at the left, which is why I bring this up. Have you tried centering the icons and setting a fixed distance between the icons? So like this (photoshopped):
![Screen Shot 2020-09-02 at 04 28 16](https://user-images.githubusercontent.com/16017904/91958226-0daf4180-ecd5-11ea-926b-ad759ccce344.png)
 Imo this is the closest to your idea of separating the URL bar and having browsers in a dynamically sized window.

**Comment by will-stone** [comment] 2020-09-02 08:58
Nice! Looks like it'll stretch my flexbox skills (no pun intended) but I'll give it a go later. Thanks.

**Comment by Kulcanhez** [comment] 2020-09-02 09:19
I like this new design, feel really clean. However, I would love to see a bit more space between icons so it can breathe better.

**Comment by will-stone** [comment] 2020-09-02 09:23
Thanks @Kulcanhez, I really appreciate the kind words. This is great to have constructive feedback; please, if anyone else stumbles upon this thread, keep it going.

I'll have a go at centering and adding a bit more padding. It'll be a good segway to my v12 idea above.

**Comment by will-stone** [comment] 2020-09-02 09:33
Ah, I just remembered why I'm not a fan of the floating design. What would you expect if clicked here?

<img width="830" alt="image" src="https://user-images.githubusercontent.com/654103/91964476-128ce900-ed07-11ea-8c38-eb1b7f7b13d5.png">

You'd expect it to close and click through to behind, right? Well, to achieve this design, you make the window transparent and have to turn off the mouse registering when hovering over the transparent parts. This is an annoying hack. So let's shelve that idea for now and tinker with v11's style first.

**Comment by RealDyllon** [comment] 2020-09-02 09:38
@will-stone 
You might want to center each icon within it's parent (flex-child), resulting in: 
<img width="912" alt="IMAGE" src="https://user-images.githubusercontent.com/25902208/91965439-0fafe980-ed43-11ea-9c2d-dadeebb8ceb1.png">

**Comment by will-stone** [comment] 2020-09-02 10:12
Thanks @RealDyllon, we'll get to Big Sur when I've installed it 😁

I'm not sure we want them that far apart. I'll try @i0ntempest's idea first, and report back.

**Comment by will-stone** [comment] 2020-09-02 10:17
I've just realised, @RealDyllon, you're running the actual code, I thought it was a photoshop at first. The box model currently looks a bit like this:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/654103/91969277-c002fb00-ed0d-11ea-8544-000d0b09bb9e.png">

As you can see, this was to give the favourite maximum space, whilst making sure the statusbar is always below the normal tiles. This is where the centering could get tricky. Maybe it won't, maybe it'll be easy 🤞

**Comment by RealDyllon** [comment] 2020-09-02 10:27
@will-stone, my image is in fact photoshop, glad you thought highly of it!

Looking at your wireframe, we could move the favourite tag to the following places:

1. Next to the trigger key
<img width="912" alt="91948351-bec6d380-ecf7-11ea-897a-2c90aff39d1a-2" src="https://user-images.githubusercontent.com/25902208/91970055-ac758580-ed49-11ea-9ef7-d243d44b1278.png">

2. Below the trigger key (perhaps floating above the bottom statusbar
![91948351-bec6d380-ecf7-11ea-897a-3c90aff39d1a-2](https://user-images.githubusercontent.com/25902208/91970143-cc0cae00-ed49-11ea-9927-c648c29b9101.png)

**Comment by will-stone** [comment] 2020-09-02 10:40
Ah, I saw the "dev" label in the version and thought you were running the code 🤓

I was aiming to have the favourite slightly larger, however it'll probably get squashed or end up being the same as the normal tiles if we include it in the box above the statusbar. Also, the gap is too large, in my opinion, and the tiles should be centered together, if we're going to center at all.

Nice though, keep all the ideas coming.

**Comment by davidbdeath** [comment] 2020-09-02 21:31
I thought the app somehow got corrupted on my computer. I'm also not a fan of the new design. From a visual design perspective, it's broken. Couldn't the interface be dynamic and change based on the number of browsers?

**Comment by will-stone** [comment] 2020-09-03 06:17
Careful @davidbdeath. Remember a single real human has worked on this, not a big corporation, and provided it for free. I know change can be polarising but please provide suggestions, not "it's broken". How would you like it to change? You can PR, or photoshop like others have done above, or even scribbles on a bit of paper can be useful.

My main motivator for this was that I didn’t want the tiles to be split on to separate rows any more (when there’s more than 5). I also thought that I could update it to be a bit flatter and minimal to go with the upcoming Big Sur design.

**Comment by i0ntempest** [comment] 2020-09-03 12:43
Speaking about Big Sur, B is not offered as an option in the default browser drop down list. After another 2 betas if this doesn’t change I’ll open a new issue.

**Comment by davidbdeath** [comment] 2020-09-03 13:30
@will-stone I gave constructive criticism. Aside from the new design being visually unbalanced. The old design's UX provided useful information on the main screen that the new one lacks, hotkey, and favorite browser. You could do an if? If (num of browsers > 5) {use this layout}else{use this layout}. I don't now typescript but after work, I might be able to tinker.

**Comment by will-stone** [comment] 2020-09-03 14:35
Thanks @i0ntempest I wonder if Big Sur has changed the way apps can register as browsers 🤔 One for when I upgrade. Don't worry, I like to upgrade on release day so I'll soon face the same bugs.

**Comment by cocoonkid** [comment] 2020-09-04 07:19
Could you add a switch for the names back ? I also liked v10 layout a lot more. But I fully understand your concerns tho 👍 

Slippery slope :)

**Comment by will-stone** [comment] 2020-09-04 07:37
I think the general layout is good. It goes well with the macOS aesthetics. For example, the dock doesn't have labels (until you hover). I've been busy recently with other projects and work, but I'll have a go at trying to centre the icons as soon as I can. I'm unsure yet how to do that without losing the height on the favourite but that may have to be the compromise, it's fairly subtly when you only have a few browsers anyway.

**Comment by i0ntempest** [comment] 2020-09-04 07:40
Just an idea, how about making B show label on hover as well?

**Comment by mindfulsource** [comment] 2020-09-06 09:27
My feedback (sorry if already given):

Items with a shortcut key attached shouldn't push them out of alignment if you have as many as me :)

Screen:
![scree](https://user-images.githubusercontent.com/59183412/92322773-a1d32d00-f076-11ea-8d12-45b6fe81add4.png)
(And yes, you can see why I need Browsersaurus. I AM Browsersaurus. RAWWWWR.)

**Comment by will-stone** [comment] 2020-09-06 11:18
@mindfulsource wow, that's a lot of browsers. You can hide them if you find you never really need to open links in them. However, good to know we have both ends of the browser-number spectrum.

As for the bug, that's weird because I'm sure I tested this but there were a lot of changes in v11 before it was releases, so maybe I missed it. I'll try to solve this first before I get on to the centre alignment. Thanks.

**Comment by will-stone** [comment] 2020-09-06 21:02
Hi all,

I've updated B to v11.1.0 with a new center-aligned layout. There seems to be a bug that means it's not hiding from the dock, and therefore the cmd-tab cycle. This is annoying, I know, and I'll see if it's an issue with a recent version of Electron.

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/654103/92335169-85da8600-f08c-11ea-991a-c7c0b002e0f5.png">

**Comment by will-stone** [comment] 2020-09-11 09:11
Going to close this now that v12 is out. Thanks all for the feedback.

**Closed by will-stone** 2020-09-11 09:11 UTC
