### ISSUE TITLE
Not working as expected in full screens

### ISSUE THREAD

**Issue by gnanirahulnutakki** [will-stone/browserosaurus#694] opened 2024-07-23 16:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

When on a full screen on Mac M1, and when the screen changes to default desktop screen to give options, I am constantly needed to reopen the last closed URL, or restart multiple times

### Expected Behaviour

Should maintain the session and show options even when, giving the options to open the required browser when link is clicked on from any Fullscreen app, that is open 4-5 apps right to default home screen

### Steps To Reproduce

- Open 3-4 apps
- Make them all full screen and open them either on right on left
- Go to the app on the extreme left or right
- Open a link
- The options to select browser opens and closes in split second

### Browserosaurus version

20.8.0

### macOS version

Sonoma 14.4.1

### CPU Architecture

ARM

### Anything else?

NA

**Comment by will-stone** [comment] 2024-07-23 20:11
Dupe of #595

**Closed by will-stone** 2024-07-23 20:11 UTC
Labels: bug
