### ISSUE TITLE
Sometimes working not properly when using multiple "spaces"

### ISSUE THREAD

**Issue by scholl1** [will-stone/browserosaurus#693] opened 2024-07-16 06:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/main/guide/supporting-a-browser-or-app.md).

### Current Behaviour

When using multiple spaces on macOS there is a condition when clicking a link in space, browserosaurus jumps to another space and the selection window for the different browsers imediatly disappaers.
A restart of the app is the only way to get back to expected condition.

### Expected Behaviour

Browserselector opens up on current space next to the link that were clicked

### Steps To Reproduce

Click on a link
(usually it appears after a while including some sleep cylces of the mac)

### Browserosaurus version

20.8.0

### macOS version

14.5

### CPU Architecture

ARM

**Comment by will-stone** [comment] 2024-07-16 06:11
Thanks. This sounds like a dupe of https://github.com/will-stone/browserosaurus/issues/595

**Closed by will-stone** 2024-07-16 06:11 UTC
Labels: bug
