### ISSUE TITLE
Unable to open links from terminal

### ISSUE THREAD

**Issue by maharjanaman** [will-stone/browserosaurus#148] opened 2019-11-04 08:04 UTC
I use iTerm and I cannot open links from terminal.

**Comment by will-stone** [comment] 2019-11-04 08:37
Do you mean `command-click`? Works for me in iTerm:

![screencast 2019-11-04 8 am-35-33](https://user-images.githubusercontent.com/654103/68107937-3a8c9f80-fede-11e9-94df-5186f2e32029.gif)

**Comment by maharjanaman** [comment] 2019-11-04 08:41
Can you try that in fullscreen mode?

**Comment by will-stone** [comment] 2019-11-04 08:45
Yep, still working fine 😕

**Comment by maharjanaman** [comment] 2019-11-04 09:24
If it helps, I'm using iTerm build `3.3.6` and on macOS Catalina 10.15.1
Works perfectly when not on fullscreen. I entered iTerm fullscreen mode using `command-return`.

**Comment by will-stone** [comment] 2019-11-04 09:26
I have same setup. What happens exactly when you command click a link in full screen? Also, which version of Browserosaurus are you using? Click the menubar icon to find the version number.

**Comment by maharjanaman** [comment] 2019-11-04 09:56
I think I've latest one i.e. `8.0.1`. I found something new here. So when I try to open link on fullscreen mode and switch to Desktop 1, there I see browserosaurus options.

**Comment by will-stone** [comment] 2019-11-04 09:59
Ah, what's your setting for "displays have separate spaces"?

![image](https://user-images.githubusercontent.com/654103/68112650-b3452900-fee9-11e9-9521-d5407405748f.png)

**Comment by maharjanaman** [comment] 2019-11-04 10:06
Yep, unchecking that option seems to be working now.

**Comment by tudoramariei** [comment] 2019-11-04 11:14
Same problem seems to happen on other apps as well if they're full screen

Screen recording of trying to open a link from Slack:
https://drive.google.com/open?id=14J3Nlo_Zt_aRZs94xvZttJkZOkUXIMAy
- the transition to the white screen is me managing to open Chrome after selecting the text and hitting space

 - OS: macOS 10.15.1 (Catalina, last update)
 - Version 8.0.1

Also, I'd rather I didn't have to give up on `Displays have separate Spaces` since that would pretty much break my workflow

**Comment by will-stone** [comment] 2019-11-04 11:21
Thanks @tudoramariei. I totally agree about not having to change that option. This may be a limitation of Electron, however I'll mark this as a bug and hopefully a fix is possible.

**Comment by will-stone** [comment] 2019-11-05 21:50
Looks like this isn't possible yet without a plugin, that I'm not sure I'm comfortable using. Hopefully it'll make into Electron as a first-class API.

https://github.com/electron/electron/issues/4939

**Comment by GaldanM** [comment] 2019-11-07 08:49
Hey @will-stone,

Just checked this issue coming from #136, even when unchecking `Displays have separate Spaces`, same behaviour happen 😕

I hope Electron will fix that soon !

**Comment by will-stone** [comment] 2019-11-07 08:58
@GaldanM I'm getting it now too. I actually updated B to use the latest Electron, the other day. We were using v5 and now it's on v7. I'm not really sure it's a _fix_ per se that's required, more that it needs a new feature added to allow windows above all others, à la Alfred or Spotlight.

**Comment by PierrickGT** [comment] 2019-11-20 09:23
I've found a way to make it work. 
If I quit Browserosaurus and then open a link in a fullscreen app, it will launch Browserosaurus to open this link and then it will display and work correctly. Seems to be the most efficient way to make it work for fullscreen apps.

**Comment by will-stone** [comment] 2019-11-20 09:32
@PierrickGT Do you need to quit B before each time a link is opened in a fullscreen app?

Side rant: I sometimes feel like I'm the only person who doesn't use fullscreen mode; I just never click that green button. Yes, I make apps the size of my screen (I use an app called Magnet which maps ctrl-alt-enter to maximise) but never full screen. I feel like all that moving between screens gets a bit too much; I don't want my windows to be _in motion_ when I change between them, when cmd-tab is instant.

**Comment by PierrickGT** [comment] 2019-11-20 09:37
@will-stone no, it works as normal once a link is opened in a fullscreen app.

**Comment by tudoramariei** [comment] 2019-11-20 09:46
Something that seems to have worked (or who knows) is to open the app non-fullscreen and then full-screen it
I tried this with Slack and what happened is...
1. I quit `B` as @PierrickGT mentioned, then clicked a link in fullscreen Slack and `B` appeared
2. clicked another time and `B` didn't appear (maybe a glitch in the matrix)
3. after click 3, `B` was already appearing consistently with Slack in fullscreen mode and without quitting it anymore

Side rant reply: In my case, I just keep some applications on fullscreen (i.e. Slack, VS Code) since I don't have multiple windows or other similar features here. I use mission control quite a lot and it helps to see the name of the app instead of the generic `Desktop #`

**Comment by will-stone** [comment] 2020-01-18 19:49
I have a feeling that the fix for #166 may have also fixed this. Maybe. 🤞

Could someone please check once you receive the 9.0.1 update?

**Comment by tudoramariei** [comment] 2020-01-20 08:34
Just tested the new version and the app seems to be working fine now 🙌 🎉 🎊 
Would like to see at least one more person confirming this since the behaviour was rather inconsistent since my last message 😅

**Comment by maharjanaman** [comment] 2020-01-20 08:37
I find it working as well. Sometimes I've to quit the app and start it again but its working fine now.

**Comment by will-stone** [comment] 2020-01-20 08:48
Nice! Well, let's close this out and if anyone notices it not working again, feel free to reopen.

**Comment by maharjanaman** [comment] 2020-02-19 04:11
@will-stone I'm seeing similar issue with latest version i.e. 9.2.0. Thanks
![Kapture 2020-02-19 at 9 53 16](https://user-images.githubusercontent.com/14164484/74801181-f80c9880-52fd-11ea-93b3-cf3799271514.gif)

**Comment by will-stone** [comment] 2020-02-19 07:00
@maharjanaman I've just been through the app to familiarise myself with the issue and it seems like a lot of restarting of B and other apps/OS _fixed_ the problem. You tried all of that?

**Comment by maharjanaman** [comment] 2020-02-19 07:32
@will-stone no luck for me. Tried restarting the os and B app multiple times.

**Comment by will-stone** [comment] 2020-02-19 08:44
I can confirm it too. Please trawl Electron's repo for a fix as it appears they are the cause.

**Comment by will-stone** [comment] 2020-02-19 13:45
Closing this out in favour of https://github.com/will-stone/browserosaurus/issues/175

**Closed by will-stone** 2020-02-19 13:45 UTC
Labels: bug, help wanted
