### ISSUE TITLE
JavaScript error when opening multiple links (that opens Browserosaurus)

### ISSUE THREAD

**Issue by Jackymancs4** [will-stone/browserosaurus#6] opened 2017-11-14 15:05 UTC
* App version: 1.0.3
* Operating system: macOS 10.13.1

### Actual behavior

With the app closed, if I open more than one link before it's ready
it throw an error alert and then randomly close the main process or keep running without responding in background.

<img width="466" alt="schermata 2017-11-13 alle 23 59 37" src="https://user-images.githubusercontent.com/6209647/32786611-bb6e57c2-c954-11e7-84e9-78a1d22cacdf.png">

### Expected behavior

I would expect the app to show the last clicked link when ready.

**Comment by will-stone** [comment] 2017-11-14 15:19
Thanks for reporting it. Yeah, it's a known issue, I just haven't gotten around to fixing it ... my workaround so far has been to leave Browserosaurus running :)

I think I know the fix:

Move the `appIsReady = true` line inside of the findInstalledBrowsers promise:

```js
app.on('ready', () => {
  // Prompt to set as default browser
  app.setAsDefaultProtocolClient('http')

  findInstalledBrowsers().then(installedBrowsers => {
    createPickerWindow(installedBrowsers.length, () => {
      pickerWindow.once('ready-to-show', () => {
        pickerWindow.webContents.send('installedBrowsers', installedBrowsers)
        if (global.URLToOpen) {
          sendUrlToRenderer(global.URLToOpen)
          global.URLToOpen = null
        }
        appIsReady = true
        // pickerWindow.webContents.openDevTools({ mode: 'detach' })
      })
    })
  })
})
```

I haven't got time to test this today but feel free to give it a go if you'd like to get into Electron development (it's really not that scary).

**Comment by Jackymancs4** [comment] 2017-11-14 16:38
Works like a charm 👍 Thank you! Mind if I do a PR?

**Comment by will-stone** [comment] 2017-11-14 22:17
Merged will release in a moment

**Closed by will-stone** 2017-11-14 22:17 UTC

**Comment by Ornataweaver** [comment] 2017-11-15 16:24
The app is too large for a simple app. 152 MBs, is this the problem with all electron apps?

**Comment by will-stone** [comment] 2017-11-15 16:26
A known issue: https://github.com/will-stone/browserosaurus/issues/9#issuecomment-344621442

**Comment by Jackymancs4** [comment] 2017-11-15 16:29
@Ornataweaver Consider that 150Mb is the min you'll get.. and yes, it's (generally speaking) common to all electron apps

**Comment by will-stone** [comment] 2017-11-15 16:31
When zipped, it should go down to ~58MB. I'll try fixing it tonight/tomorrow.

**Comment by Ornataweaver** [comment] 2017-11-15 16:34
Still downloading with 2Mb/second bandwidth. (about 200 KB/s)

**Comment by will-stone** [comment] 2017-11-15 16:36
Oh, sorry. ~58MB is the best it'll ever be for an Electron app. Although I did read of someone who'd started a project whereby it uses Safari's JS engine underneath instead of shipping Chrome's V8 with each app and it brought the size of things down to mere megabytes. Not sure if it took off though.

**Comment by Ornataweaver** [comment] 2017-11-15 16:47
58MB is very good. The problem is with electron.
If there would be an electron builder for end-users, your app could only download the new code, and build the update on user side.

**Comment by Ornataweaver** [comment] 2017-11-15 16:50
Or if there was some electron daemon running in the background, so every electron app would invoke it and use it. And if it was not present, Electron apps would prompt the user for downloading electron.
That would reduce the size of all apps on this popular platform.

**Comment by will-stone** [comment] 2017-11-15 16:51
Indeed, that would be awesome. Sounds like a good issue to log with Electron devs themselves. If you do, post a link to it here so I can up-vote it.
