### ISSUE TITLE
When internet connection is lost, browserosaurus shows  a popup

### ISSUE THREAD

**Issue by rushiagr** [will-stone/browserosaurus#162] opened 2019-12-07 06:54 UTC
**Describe the bug**
When internet connection is lost, browserosaurus shows  a popup. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn wifi off of laptop

**Expected behaviour**
Shouldn't show a popup and distract the user.

**Screenshots**

<img width="416" alt="Screenshot 2019-12-07 at 12 09 57 PM" src="https://user-images.githubusercontent.com/1409020/70370353-5247b100-18ec-11ea-9d0a-a72bd788b59b.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Version: v6.7.0

**Additional context**
n/a

**Comment by will-stone** [comment] 2019-12-07 08:23
This looks to be the cause: https://github.com/electron-userland/electron-builder/issues/2451

**Comment by will-stone** [comment] 2020-01-18 19:11
The chat on that issue suggests that the issue has been fixed by Electron and B now uses the latest version of Electron. I'll close this as it should be covered by the upcoming v9 release. Please re-open if you still see this when using v9 or later.

**Closed by will-stone** 2020-01-18 19:11 UTC
Labels: bug
