### ISSUE TITLE
Browsers missing from picker window (URL bar shown)

### ISSUE THREAD

**Issue by anguka** [will-stone/browserosaurus#425] opened 2021-08-05 06:48 UTC
on Safari, trying to open some links causes an empty Browserosaurus screen to open – no browser icons appear from which to choose.  
 
The app appears to freeze, but if quit and then restarted, the link will open.

**Comment by will-stone** [comment] 2021-08-05 08:54
Hi. Can you please do a screen recording? Thank you 🙂

Also please state:
- macOS version.
- Browserosaurus version.

**Comment by joel-tonuri** [comment] 2021-08-06 02:12
Exact same issue here.

It usually occurs after a restart (I have Browserosaurus set to open at login, hidden in the Users & Groups pane located in System Preferences). However, it can be resolved by quitting Browserosaurus and then clicking the link again (aka reopening Browserosaurus).

Running macOS 11.5.1 on an M1 machine, Browserosaurus 15.1.2.

Screen recording below!

Thanks for your help.

https://user-images.githubusercontent.com/50507756/128445405-03f2dd3e-2e0e-4d91-a01e-926e6cf89c6e.mov

**Comment by will-stone** [comment] 2021-08-06 05:59
Thank you @joel-tonuri, this is why screenshots and videos are important: as “blank” means nothing which means it has likely suffered a JavaScript error and crashed. However, this shows the URL bar is still functioning, which means it’s a simply an issue with the scanning. I reckon this is Browserosaurus running before the Spotlight index is ready. This sounds silly but these reports are only coming in after the most recent macOS upgrade, which suggests Apple have broken something.

Does it ever happen whilst your system has been running, or is it always after system restart / logout-login?

Can you please do me a favour, and screenshot the console (open B and press command + shift + i) when this next happens?

**Comment by joel-tonuri** [comment] 2021-08-06 08:12
>I reckon this is Browserosaurus running before the Spotlight index is ready.

Hmm, certainly could be.
> Does it ever happen whilst your system has been running, or is it always after system restart / logout-login?

I think it has happened a few times without a restart - but it is always able to be reproduced after a restart.
> Can you please do me a favour, and screenshot the console (press command + option + i) when this next happens?

I'm not sure if this is normal, but the console tab is completely empty? See screenshot:
<img width="1205" alt="Screen Shot 2021-08-06 at 6 08 32 pm" src="https://user-images.githubusercontent.com/50507756/128478860-025b0ced-7489-4e54-b3e6-9d24951c59df.png">

**Comment by will-stone** [comment] 2021-08-06 08:23
Thank you. So this suggests no errors in the renderer process. This is not to say there isn't an error in the main process, although I thought if this happened an alert was displayed by Electron 🤔 

Do you use any network blocking tools? I'm wondering if the update checker is crashing. I definitely need to wrap it in a `try/catch`, just in case. Although just turning off wifi would replicate the issue, which it doesn't.

Hmmm... does pressing the `rescan` button in Preferences fix the issue or do you need to restart Browserosaurus completely?

**Comment by joel-tonuri** [comment] 2021-08-06 21:17
> Do you use any network blocking tools?

None at all. In fact, this is a relatively new install of macOS Big Sur (around 1-2 weeks since installation), so the amount of applications I have installed is minimal.
>Does pressing the rescan button in Preferences fix the issue or do you need to restart Browserosaurus completely?

I just gave this a go, and pressing the rescan button does not resolve the issue. 😞  Browserosaurus has to be fully quit and reopened for it to start functioning properly...

**Comment by will-stone** [comment] 2021-08-15 20:23
Ooo, I just experience this. However, clicking rescan fixed the issue (it may take some time on older machines). I had recently rebooted from a full system crash, so maybe this was a result of macOS trying to restore all previously open apps. Either way, it may be a race condition, I'll try to do some more research.

**Comment by will-stone** [comment] 2021-08-22 08:17
This should be fixed in v15.1.3 that's just been released. Please re-test when you get the update and let me know. Thanks.

**Closed by will-stone** 2021-08-22 08:17 UTC
Labels: more details required

**Comment by tuongpm-teko** [comment] 2021-08-22 13:24
I'm using Macbook Pro 13 2017, which version is suitable for me?
I have tried 15.1.5 but it seems not support
