### ISSUE TITLE
Ability to set custom rules?

### ISSUE THREAD

**Issue by sinat101** [will-stone/browserosaurus#53] opened 2018-04-12 17:44 UTC
Instead of always choosing which browser to use, would it be possible to add support of custom rules? Such as "if link is launching from HipChat (or any other application) then launch in Chrome (or whatever browser you choose)".

**Comment by will-stone** [comment] 2018-04-12 19:15
Duplicate of #32.

**Closed by will-stone** 2018-04-12 19:15 UTC
Labels: duplicate
