### ISSUE TITLE
Feedback: Pop up be same width as number of browser items

### ISSUE THREAD

**Issue by maharjanaman** [will-stone/browserosaurus#289] opened 2020-09-02 09:03 UTC
Can browserosaurus popup be same width as number of available brower in the system? Currently, it takes fixed width and shows long empty space.
<img width="912" alt="Screen Shot 2020-09-02 at 14 39 02" src="https://user-images.githubusercontent.com/14164484/91961476-f0a55d80-ed2a-11ea-8321-83914abca081.png">

Also, can we have option to make browserosaurus popup at either center of screen or at cursor position? I think this feature will make browserosaurus more awesome. 😁

**Comment by will-stone** [comment] 2020-09-02 09:17
Hi. Please follow along at #288 as we're thinking of putting the browsers in the centre. The problem is that we need the URL bar to have length so that the URL isn't hidden too much.

Weirdly, the picker already opens where Electron thinks is the center of the window: https://github.com/will-stone/browserosaurus/blob/4c17deb34a59ec3a7d5574c9a278b0648c56c381/src/main/createWindow.ts#L45

As for "at cursor", I'm going to have to decline. This is how Browserosaurus used to work but required so many hacks that caused bugs on each Electron and macOS release that I just didn't feel comfortable with maintaining it any more. I found I was mainly using the keyboard, and decided it was best for the future of Browserosaurus if I changed tack.

Thanks for using B, and for the feedback. I'm going to close this in favour of #288.

**Closed by will-stone** 2020-09-02 09:17 UTC
