### ISSUE TITLE
[Bug]Sometimes chrome of Windows 10 in Parallels Desktop is detected

### ISSUE THREAD

**Issue by hstdt** [will-stone/browserosaurus#108] opened 2019-06-24 02:27 UTC
I want to use the mac chrome, but sometimes a windows 10 chrome is detected.
(Browserosaurus v6.1.0)

PS: Microsoft Edge can not be detected.
![image](https://user-images.githubusercontent.com/10215098/59986806-e7baf580-966a-11e9-96d3-c86740269122.png)

**Comment by will-stone** [comment] 2019-06-24 06:26
Interesting. That’s not one I’m going to be able to test for myself, unfortunately, as I own neither Parallels nor W10, so you’ll need to do the leg work here. If it’s opening the Chrome installed on the VM, that means the command `open http://example.com -a “Google Chrome”` is doing that. If your computer is mapping that to the other Chrome there’s not much I can do. All B does is use the system profiler to list every app installed and then, using a whitelist, narrow that down to a list of browsers that B knows about. I suggest starting by trying to figure out why it only sometimes happens and reliably narrowing down the steps to reproduce it every time.

**Comment by eucrasia** [comment] 2019-08-04 08:52
I also had this issue. And the command `open http://example.com -a "Google Chrome"` did open the Chrome app on Parallels.

Renaming the Google Chrome helper app created by Parallels (`~/Applications (Parallels)/${Parallels VM Name} Applications/Google Chrome.app`) to some other name (e.g. `Google Chrome (Windows 10).app`) solved the issue for now.

I think https://github.com/facebook/react-native/issues/11480#issuecomment-307465821 is another, more permanent solution, but I didn't like it because I find the feature somewhat useful which allows for sharing Win apps with Mac.

**Comment by will-stone** [comment] 2019-10-26 11:49
@hstdt @eucrasia Can you please confirm this is now fixed? Current version is v6.6.1

**Comment by hstdt** [comment] 2019-10-27 02:31
@will-stone It fixed. Thanks!

**Closed** 2019-10-27 07:00 UTC
Labels: more details required

**Comment by eucrasia** [comment] 2019-10-27 12:50
Have confirmed that the issue has gone with v6.6.3 + Parallels Desktop 15.1.0 + macOS 10.15. Thanks for the great work!
