### ISSUE TITLE
Handoff support, please.

### ISSUE THREAD

**Issue by Victorio115** [will-stone/browserosaurus#99] opened 2019-06-02 22:10 UTC
Handoff is a function that allows open certain files opened on one Apple Device on another Apple Device. Example: Open a Pages Document opened on an iPhone, on a MacBook Air.  
  
I have set Browserosaurus as my default browser on my MacBook, I have a website opened on my iPhone, my MacBook is suggesting me to open that website on Safari.  
  
Will be possible for you, add Handoff support?

**Comment by will-stone** [comment] 2019-06-03 08:02
Hi, thanks for using Browserosaurus and for the suggestion. I think this may be by design by Apple. Could you please do some experimenting to see if handoff to other browsers is even possible?

1. Chrome as default on macOS, Safari used on iPhone. Which browser does handoff prompt you to use?
2. Firefox as default on macOS, Safari used on iPhone. Which browser does handoff prompt you to use?
3. Chrome as default on macOS, Chrome used on iPhone. Which browser does handoff prompt you to use?
4. Safari as default on macOS, Chrome used on iPhone. Which browser does handoff prompt you to use?

I have a feeling it's only Safari to Safari, rather than Safari to Default Mac Browser. Having said that, it looks like Electron can hook into handoff events: https://github.com/electron/electron/blob/master/docs/api/app.md#event-continue-activity-macos I'd have to do some experimenting myself.

**Comment by Victorio115** [comment] 2019-06-09 08:19
1. I won't use Google Chrome, I will use Brave instead. My Mac prompts Brave Browser.
2. My Mac prompts Firefox.
3. Using Brave Browser for iOS, My Mac prompts Brave Browser.
4. My Mac prompts Safari.
Was that enough information?

**Comment by will-stone** [comment] 2019-06-09 08:34
That’s great, thanks. I’ll add this to the backlog (feel free to put in a PR if you’d like this sooner).

**Comment by Victorio115** [comment] 2019-06-09 09:14
What do you mean with "PR"?

**Comment by will-stone** [comment] 2019-06-09 11:00
Pull request. This project is open-source, meaning if you know TypeScript/JavaScript you can look at the code, make the modifications you like, and send them to me as a request to "pull" in your changes.

**Comment by will-stone** [comment] 2019-08-29 06:24
I've had a look at this and unfortunately can't get Electron to recognise Hand-Off passing to it. I'll leave this open in case any one finds this issue and knows how to implement Hand-Off.

**Comment by will-stone** [comment] 2019-11-06 12:43
@Victorio115 Although not handoff, my colleague found out today that you can use airdrop. Sending a webpage, via airdrop, to your mac will activate Browserosaurus 🥳

**Comment by will-stone** [comment] 2020-06-07 17:02
I'm going to close this as I have been using Airdrop to send links from my phone to Browserosaurus for ages now, and I don't think handoff would really add much benefit over this flow.

**Closed by will-stone** 2020-06-07 17:02 UTC
Labels: enhancement, help wanted
