### ISSUE TITLE
Ventura virtual desktop compatibility

### ISSUE THREAD

**Issue by faebe** [will-stone/browserosaurus#582] opened 2022-11-03 09:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Since MacOS Ventura when the app was previously opened on another virtual desktop and a link is clicked on a different virtual desktop the desktop will switch to that previous virtual desktop but the browser selector UI will not show / disappear immediately. Quitting and restarting the app solves the issue temporarily every time.

### Expected Behaviour

The browser selector UI should appear on the current virtual desktop in the foreground, no matter what virtual desktop it was opened on previously.

### Steps To Reproduce

1. Install MacOS Ventura
2. Open a link on a virtual desktop using Browserosaurus
3. Go to another virtual desktop
4. Open another link using Browserosaurus

### Browserosaurus version

19.1.0

### macOS version

13.0

### CPU Architecture

ARM

**Comment by will-stone** [comment] 2022-11-03 09:21
Hi @faebe Thank you for reporting. I don't currently have time to look into this issue, and I don't use virtual desktops so it's not a priority for me. I'd gladly review a pull request if you'd like to submit one 🙂

**Comment by roastedduk** [comment] 2022-11-04 07:34
Can confirm I have this issue too with latest stable Ventura release.

**Comment by will-stone** [comment] 2022-11-04 09:19
Thanks @roastedduk. Happy to review a PR if you find the culprit 😄

**Comment by will-stone** [comment] 2022-11-08 10:10
Hi @faebe @roastedduk Could you please do a screen recording of the issue you're facing as it seems to be working okay when I try it. Here's my setup:
- macOS 13.0 (M2)
- B 19.1.0

**Comment by roastedduk** [comment] 2022-11-08 17:10
Hey sorry for the late reply. I can't seem to reproduce the issue anymore after restarting. Not sure what happened but it's working fine now.

**Comment by roastedduk** [comment] 2022-11-09 05:47
https://user-images.githubusercontent.com/105736696/200748895-af5e13fe-c297-4275-b312-380da778cf8c.mp4

Nvm, encountered the bug again, B 19.1.0, Ventura 13.0. Hope this helps!

**Comment by y-mx-b** [comment] 2022-11-12 10:59
I've seen this bug pop up now and again since either Big Sur or Catalina. I'm not entirely sure why this happens, and it's not easily reproducible. Quitting and reopening the app tends to fix it though.

**Comment by flacial** [comment] 2022-11-13 14:48
I tried to reproduce it in the development app (19.2.0), but it doesn't occur at all. However, it seems to be related to [electron workspace API](https://github.com/electron/electron/issues/5362)

@roastedduk @faebe may you share how to reproduce it? It'll help in finding the _culprit_

**Comment by roastedduk** [comment] 2022-11-13 15:01
> I tried to reproduce it in the development app (19.2.0), but it doesn't occur at all. However, it seems to be related to [electron workspace API](https://github.com/electron/electron/issues/5362)
> 
> @roastedduk @faebe may you share how to reproduce it? It'll help in finding the _culprit_

It's still happening with 19.2.0 for me, but same as @y-mx-b it happens randomly and not easily reproducible so I'm not sure too. But when it happens it will keep bugging until I restart the app.

**Comment by joelmgallant** [comment] 2022-11-14 10:14
Agreed - I see this pretty frequently.
First; love this software, it's an absolute gem - and thank you for it!

Generally I have a setup with:
- 2 virtual desktops
- 2 browsers (one Safari, one Vivaldi)
 - one on each VD

The behaviour I observe often has these characteristics:
- open link on one VD
- OS auto-switches to second VD to display popup
- popup is shown briefly before other windows appear in front.

My original theory: external monitor / docking & undocking - it would tend to happen after detaching from a larger monitor space, laptop going to sleep, re-opening later.

This _doesn't_ seem like the whole story though - I just experienced this on resume from sleep *without* attaching a monitor in between.

Killing the app processes & restarting them resolves the issue.

I'm also of the opinion this is probably Electron-related -- if I manage to debug I'll happily PR it!

**Comment by porcherie** [comment] 2022-12-01 21:39
For me it is easily reproducible, I made a video recording where you can see how it happens
https://www.loom.com/share/768eb91aa8a0463a9a86d92e4b6a355c

I'm on Ventura 13.0.1 on a MacBook Pro 16 M1

**Comment by iljamm** [comment] 2022-12-02 09:38
Getting exact same issue as [@porcherie](https://github.com/will-stone/browserosaurus/issues/582#issuecomment-1334481813)

![image](https://user-images.githubusercontent.com/20164908/205262678-7617a6e9-c490-49f1-989a-82f5825f3e2c.png)

**Comment by riotrah** [comment] 2022-12-11 22:54
I think this is (probably) a duplicate of #136 #356 #595

**Comment by kirkbig** [comment] 2022-12-12 23:30
i have seen this issue a lot as well.  i love this product, but since venture, i've had to load most of my apps into a single virtual desktop to get it working reliably.

**Comment by will-stone** [comment] 2022-12-16 22:14
Let’s close this in favour of #595

**Closed by will-stone** 2022-12-16 22:14 UTC
Labels: bug

**Comment by kirkbig** [comment] 2022-12-17 08:36
> Let’s close this in favour of https://github.com/will-stone/browserosaurus/issues/595

fwiw, the apps that i've been having difficulty with are not full-screen, though the behavior described in #595 does seem likely related.
