### ISSUE TITLE
Issues with full screen apps.

### ISSUE THREAD

**Issue by macmus82** [will-stone/browserosaurus#633] opened 2023-04-08 03:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have searched the [discussions forum](https://github.com/will-stone/browserosaurus/discussions)
- [X] I understand this form is for reporting bugs, and not for requesting [support for new browsers or apps](https://github.com/will-stone/browserosaurus/blob/master/guide/supporting-a-browser-or-app.md).

### Current Behaviour

Sometimes when app is open in full screen mode and the link is clicked the Macos change desktop before pop-up.
Once screen changed the pop-up disappears and link does not open.

### Expected Behaviour

Pop-up always open before Mac switches screen to the browser window.

### Steps To Reproduce

open app in full screen mode
click link.

Not always reproducible. 

WA is to exit fullscreen and reenter.

### Browserosaurus version

20.2

### macOS version

13.3.1

### CPU Architecture

ARM

**Comment by will-stone** [comment] 2023-04-08 06:32
Thanks but dupe of https://github.com/will-stone/browserosaurus/issues/595

**Closed by will-stone** 2023-04-08 06:32 UTC
Labels: bug
